# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile

# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system dependencies if necessary
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the project files into the container
COPY . /app

# Upgrade pip
RUN pip install --upgrade pip

# Install the package in editable mode
RUN pip install -e .

# Expose ports if needed (MCP communicates over stdio, so not strictly necessary)

# Command to run the server using python directly
CMD ["python", "-m", "src.stela_mcp.server"]
