[project]
name = "stela-mcp"
version = "0.1.0"
description = "MCP server for local system operations"
readme = "README.md"
authors = [
    { name = "Sachin Bhat", email = "sachubhat17@gmail.com" }
]
dependencies = [
    "mcp[cli]>=1.1.0",
    "typing-extensions>=4.13.0"
]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
